proxies:
  - proxy01
  - proxy02
  - proxy03
  - proxy04
  - proxy05
  - proxy06
  - proxy07
  - proxy08
  - proxy09
  - proxy10
  - proxy11
  - proxy12
  - proxy13
  - proxy14
  - proxy15
  - proxy16
  - proxy17
  - proxy18
  - proxy19
  - proxy20
  - proxy21
